/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jMDIForm;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author oppew
 */
public class ChoiceMethodPageRankDialog extends javax.swing.JDialog {

    int selectedMethod = 1;
    int iterations = 0;
    double accuracy = 0;
    public double d = 0.85;
    /**
     * Creates new form ChoiceMethodPageRankDialog
     */
    public ChoiceMethodPageRankDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                // Автоматически подгоняем размер окна под содержимое
        pack();
        
        // Центрируем относительно экрана
        setLocationRelativeTo(null);
        
    }
    
    public ChoiceMethodPageRankDialog(java.awt.Frame parent, boolean modal, boolean isStatic, jMDIFrame MDIFrame) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.show();
        if (isStatic)
            StaticPageRank(MDIFrame);
        else
            DynamicPageRank();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpenChooser = new javax.swing.JFileChooser();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        IterationRadioButton = new javax.swing.JRadioButton();
        AccuracyRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextPane = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Properties");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        OKButton.setText("OK");
        OKButton.setActionCommand("Ok");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PageRank algorithm"));
        jPanel1.setToolTipText("");

        IterationRadioButton.setSelected(true);
        IterationRadioButton.setText("Iteration");
        IterationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IterationRadioButtonActionPerformed(evt);
            }
        });

        AccuracyRadioButton.setText("Accuracy");
        AccuracyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccuracyRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Number of iterations/accuracy:");

        TextPane.setText("10");
        jScrollPane2.setViewportView(TextPane);

        jLabel3.setText("Value of d param:");

        jTextPane1.setText("0.85");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IterationRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AccuracyRadioButton))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IterationRadioButton)
                            .addComponent(AccuracyRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OKButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(OKButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IterationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IterationRadioButtonActionPerformed
         IterationRadioButton.setSelected(true);
         AccuracyRadioButton.setSelected(false);
         TextPane.setText("10");
         selectedMethod = 1;
    }//GEN-LAST:event_IterationRadioButtonActionPerformed

    private void AccuracyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccuracyRadioButtonActionPerformed
        IterationRadioButton.setSelected(false);
         AccuracyRadioButton.setSelected(true);
         TextPane.setText("0.01");
         selectedMethod = 2;
    }//GEN-LAST:event_AccuracyRadioButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        d = Double.parseDouble(jTextPane1.getText());
        if (d >= 1 || d <= 0)
            JOptionPane.showMessageDialog(this, "Incorrect input damping coefficient! Enter number between 0 and 1.", "damping coefficient", JOptionPane.WARNING_MESSAGE);
        else {
            if (selectedMethod == 1) {
                iterations = Integer.parseInt(TextPane.getText());
                if (iterations < 1)
                    JOptionPane.showMessageDialog(this, "Incorrect input! Enter natural number.", "Choise method", JOptionPane.WARNING_MESSAGE);
                else {
                    dispose();
                }
            }
            else if (selectedMethod == 2) {
                accuracy = Double.parseDouble(TextPane.getText());
                if (accuracy >= 1 || accuracy <= 0)
                    JOptionPane.showMessageDialog(this, "Incorrect input! Enter number between 0 and 1.", "Choise method", JOptionPane.WARNING_MESSAGE);
                else {
                    dispose();
                }
            }
        }
    }//GEN-LAST:event_OKButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        selectedMethod = 0;
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        selectedMethod = 0;
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoiceMethodPageRankDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoiceMethodPageRankDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoiceMethodPageRankDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoiceMethodPageRankDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChoiceMethodPageRankDialog dialog = new ChoiceMethodPageRankDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public int selectedMethod() {
        return selectedMethod;
    }
    
    public int getNumberOfIterations() {
        accuracy = 0;
        return iterations;
    }
    
    public double getAccuracy() {
        iterations = 0;
        return accuracy;
    }
    private void StaticPageRank(jMDIFrame MDIFrame) {
        //передача параметров в PageRankFrame
        PageRankFrame frame = new PageRankFrame();
        if (selectedMethod != 0) {
            frame.StaticPageRank(MDIFrame, selectedMethod, iterations, accuracy, d);
            frame.setLocationRelativeTo(null);
            frame.show();
        }
    }
    
    private void DynamicPageRank() {
        //открытие XES файла
        List<String> lines = ReadXesFile();
        //передача параметров в PageRankFrame
        PageRankFrame frame = new PageRankFrame();
        if (selectedMethod != 0) {
            frame.DynamicPageRank(lines, selectedMethod, iterations, accuracy, d);
            frame.setLocationRelativeTo(null);
            frame.show();
        }
    }
    
    private List<String> ReadXesFile() {
        OpenChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        OpenChooser.setCurrentDirectory(new File("."));
        OpenChooser.setFileFilter(new FileNameExtensionFilter("XES", "XES", "xes", "csv"));
        int option = OpenChooser.showOpenDialog(this);
        List<String> lines = null;
        if(option == JFileChooser.APPROVE_OPTION)
            try {
                Path path = Path.of(OpenChooser.getSelectedFile().getAbsolutePath());
                lines = Files.readAllLines(path);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        return lines;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AccuracyRadioButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JRadioButton IterationRadioButton;
    private javax.swing.JButton OKButton;
    private javax.swing.JFileChooser OpenChooser;
    private javax.swing.JTextPane TextPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
